#!/bin/bash

# Get the list of plugins to verify
plugins=(fswatch)

# Define color variables
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Loop through the plugins
for plugin in "${plugins[@]}"; do
  echo -e "${GREEN}Verifying $plugin...${NC}"

  # Check if the plugin is installed
  if brew list "$plugin" &>/dev/null; then
    echo -e "${GREEN}$plugin is installed.${NC}"
  else
    echo -e "${YELLOW}Installing $plugin...${NC}"
    brew install "$plugin"
    echo -e "${GREEN}$plugin installed...${NC}"
  fi
done

# Check if the directory argument is provided
WATCH_DIR="$(pwd)"  # Use provided directory or default to current directory
FOLDER_MODULES_TO_WATCH="${WATCH_DIR}/docroot/modules/custom"
FOLDER_THEMES_TO_WATCH="${WATCH_DIR}/docroot/themes/custom"
FOLDER_BINARIES="${WATCH_DIR}/vendor/bin"
# Path to the Drush executable
DRUSH="${FOLDER_BINARIES}/drush"

# Action to perform when a file is modified
ACTION="$DRUSH cr"  # Clear Drupal cache

echo -e "${YELLOW}Watching $FOLDER_MODULES_TO_WATCH and $FOLDER_THEMES_TO_WATCH for changes...${NC}"

# Check if the specified directory exists
if [ ! -d "$WATCH_DIR" ]; then
    echo -e "${RED}Error: Directory '$WATCH_DIR' does not exist.${NC}"
    exit 1
fi

# Check if Drush executable exists
if [ ! -x "$DRUSH" ]; then
    echo -e "${RED}Error: Drush executable not found at '$DRUSH'.${NC}"
    exit 1
fi

clear_cache() {
  $ACTION || echo -e "${RED}Error: Failed to run '$ACTION'.${NC}"
  echo -e "${YELLOW}waiting...${NC}"
  # Add a delay to ignore subsequent saves for a brief period
  sleep 5
}

export -f clear_cache

# Use fswatch to monitor the directories for file modifications
fswatch -0 -e ".*" -i "\\.html\\.twig$" "$FOLDER_MODULES_TO_WATCH" "$FOLDER_THEMES_TO_WATCH" | while read -d "" modified_file; do
    echo -e "${GREEN}File $modified_file was modified${NC}"
    clear_cache
done

# Use fswatch to monitor the directories for file modifications
fswatch -0 -e ".*" -i "\\.inc$" "$FOLDER_MODULES_TO_WATCH" "$FOLDER_THEMES_TO_WATCH" | while read -d "" modified_file; do
    echo -e "${GREEN}File $modified_file was modified${NC}"
    clear_cache
done

# Use fswatch to monitor the directories for file modifications
fswatch -0 -e ".*" -i "\\.*\\.yml$" "$FOLDER_MODULES_TO_WATCH" "$FOLDER_THEMES_TO_WATCH" | while read -d "" modified_file; do
    echo -e "${GREEN}File $modified_file was modified${NC}"
    clear_cache
done